parameters:
  - name: 'environment'
    type: string
    default: dev
    values:
    - dev
    - prod

  - name: 'buildType'
    type: string
    default: current
    values:
    - current
    - specific
  
  - name: 'buildVersion'
    type: string
    default: latest
    values:
    - latest
    - specific
    - latestFromBranch
  
  - name: 'buildId'
    type: string
    default: ' '
  
  - name: 'branchName'
    type: string
    default: '/refs/heads/test2'
    values:
    - /refs/heads/test2
    - /refs/heads/master
    - /refs/heads/dev0
    - /refs/heads/prod
  
variables:
  - ${{ if eq(parameters.environment, 'dev') }}:
    - template: dev-variables.yaml
  - ${{ if eq(parameters.environment, 'prod') }}:
    - template: prod-variables.yaml

trigger: none

jobs:
  - deployment:
    pool: $(poolName)
    displayName: 'Deploy Terraform Modules'
    environment: '${{ parameters.environment }}'
    workspace:
      clean: all
    strategy:
      runOnce:
        deploy:
          steps:
            - ${{ if eq( parameters['buildType'], 'current') }}:
              - task: AzureCLI@2
                displayName: 'Azure CLI - Promote Service Principal'
                inputs:
                  azureSubscription: $(serviceConnection)
                  scriptType: ps
                  scriptLocation: inlineScript
                  inlineScript: |
                    Write-Host "##vso[task.setvariable variable=CLIENT_ID]$($env:servicePrincipalId)"

                    Write-Host "##vso[task.setvariable variable=CLIENT_SECRET]$($env:servicePrincipalKey)"

                    Write-Host "##vso[task.setvariable variable=TENANT_ID]$($env:tenantId)"
                  addSpnToEnvironment: true   

            - ${{ if eq( parameters['buildType'], 'current') }}:
              - task: AzurePowerShell@5
                inputs:
                  azureSubscription: $(serviceConnection)
                  ConnectedServiceNameARM: $(serviceConnection)
                  ScriptType: 'InlineScript'
                  azurePowerShellVersion: 'LatestVersion'
                  Inline: |
                    $azspkey = "$(CLIENT_SECRET)"
                    $azspid = "$(CLIENT_ID)"
                    $aztenantid = "$(TENANT_ID) "
                    $blobUri = "https://$(backendStorageAccountName).blob.core.windows.net/$(buildContainerName)/buildId.csv"
                    $body = @{
                        client_id = $azspid
                        client_secret = $azspkey
                        grant_type = "client_credentials"
                        resource = "https://storage.azure.com/"
                    }

                    $resp = Invoke-WebRequest -Uri "https://login.microsoftonline.com/$($aztenantid)/oauth2/token" -Body $body -Method Post -ContentType "application/x-www-form-urlencoded" -UseBasicParsing

                    if ($resp.statusCode -eq 200) {
                        $token = ($resp | ConvertFrom-Json).access_token
                    }

                    ##Get Blob to download using API
                    $header = @{
                      Authorization = "Bearer " + $token
                      "x-ms-version" = "2020-04-08"
                    }

                    Invoke-WebRequest -uri $blobUri -Method Get -Headers $header -OutFile .\buildId.csv
                    $values = Import-CSV .\buildId.csv
                    $buildId = $values[-1].buildId
                    Write-Host "##vso[task.setvariable variable=BUILD_ID]$($buildId)"
                    Remove-Item -Path .\buildId.csv -Force
                  workingDirectory: '$(System.ArtifactsDirectory)'

            - ${{ if eq( parameters['buildType'], 'specific') }}:
              - task: DownloadBuildArtifacts@1
                displayName: 'Download Build Artifacts'
                inputs:
                  buildType: '${{ parameters.buildType }}'
                  buildVersionToDownload: '${{ parameters.buildVersion }}'
                  buildId: '${{ parameters.buildId }}'
                  branchName: '${{ parameters.branchName }}'
                  artifactName: $(artifactName)
                  downloadType: 'single'
                  downloadPath: $(System.ArtifactsDirectory)
                  project: $(project)
                  pipeline: $(pipeline)
            
            - ${{ else }}:
              - task: DownloadBuildArtifacts@1
                displayName: 'Download Build Artifacts'
                inputs:
                  buildType: 'specific'
                  buildVersionToDownload: 'specific'
                  buildId: '$(BUILD_ID)'
                  branchName: '${{ parameters.branchName }}'
                  artifactName: $(artifactName)
                  downloadType: 'single'
                  downloadPath: $(System.ArtifactsDirectory)
                  project: $(project)
                  pipeline: $(pipeline)
        
            - task: ms-devlabs.custom-terraform-tasks.custom-terraform-installer-task.TerraformInstaller@1
              displayName: 'Install Terraform latest'
              inputs:
                terraformVersion: 'latest'

            - task: ms-devlabs.custom-terraform-tasks.custom-terraform-release-task.TerraformTaskV4@4
              displayName: 'Terraform : azurerm - Init'
              inputs:
                backendServiceArm: SharedResources
                backendAzureRmResourceGroupName: $(backendResourceGroupName)
                backendAzureRmStorageAccountName: $(backendStorageAccountName)
                backendAzureRmContainerName: $(backendContainerName)
                backendAzureRmKey: '$(moduleName)-$(environment).tfstate'
                workingDirectory: '$(System.ArtifactsDirectory)\$(artifactName)\${{ parameters.environment }}'
            
            - powershell: |
                terraform workspace new ${{ parameters.environment }}
                terraform workspace select ${{ parameters.environment }}
              displayName: 'Create and Set the Terraform workspace'
              workingDirectory: '$(System.ArtifactsDirectory)\$(artifactName)\${{ parameters.environment }}'

            - task: ms-devlabs.custom-terraform-tasks.custom-terraform-release-task.TerraformTaskV4@4
              displayName: 'Terraform : azurerm - Plan'
              inputs:
                provider: azurerm
                command: 'plan'
                workingDirectory: '$(System.ArtifactsDirectory)\$(artifactName)\${{ parameters.environment }}'
                commandOptions: '-var-file=${{ parameters.environment }}.auto.tfvars -out=${{ parameters.environment }}.tfplan'
                environmentServiceNameAzureRM: SharedResources
                                
            - task: ms-devlabs.custom-terraform-tasks.custom-terraform-release-task.TerraformTaskV4@4
              displayName: 'Terraform : azurerm - Apply'
              inputs:
                provider: azurerm
                command: 'apply'
                workingDirectory: '$(System.ArtifactsDirectory)\$(artifactName)\${{ parameters.environment }}'
                commandOptions: '-var-file=${{ parameters.environment }}.auto.tfvars -auto-approve'
                environmentServiceNameAzureRM: SharedResources