parameters:
  - name: 'environment'
    type: string
    default: dev
    values:
    - dev
    - prod
  
variables:
  - ${{ if eq(parameters.environment, 'dev') }}:
    - template: dev-variables.yaml
  - ${{ if eq(parameters.environment, 'prod') }}:
    - template: prod-variables.yaml

#Trigger from branch
trigger:
  branches:
    include:
      - prod
      - dev0

jobs:
  - job: 'BuildModule_vnetdemo'
    pool: $(poolName)
    displayName: 'Build Packages'
    workspace:
      clean: all
    steps:
    - checkout: self
      persistCredentials: true
      clean: true
      fetchDepth: true

    - task: CopyFiles@2
      displayName: 'Filter folders'
      inputs:
        Contents: |
          **
          !**\.git\**
          !**\.terraform\**
        targetFolder: $(Build.ArtifactStagingDirectory)
    
    - task: AzurePowerShell@5
      inputs:
        ConnectedServiceNameARM: $(serviceConnection)
        ScriptType: 'InlineScript'
        Inline: |
          $buildId = "$(Build.BuildId)"
          $timestamp = Get-Date -Format "yyyyMMdd_HHmmss""
          $buildNumber = "$(Build.BuildNumber)"
          $azureAplicationId ="$($env:servicePrincipalId)"
          $azureTenantId= "$($env:tenantId)"
          $azurePassword = ConvertTo-SecureString "$($env:servicePrincipalKey)" -AsPlainText -Force
          $psCred = New-Object System.Management.Automation.PSCredential($azureAplicationId , $azurePassword)
          Connect-AzAccount -Credential $psCred -TenantId $azureTenantId  -ServicePrincipal
          $storageAccountName = "$(backendStorageAccountName)"
          $resourceGroupName = "$(backendResourceGroupName)"
          $containerName = "$(buildContainerName)"
          $blobName = "buildId.csv"

          $storageAccount = Get-AzStorageAccount -ResourceGroupName $resourceGroupName -Name $storageAccountName
          $storageContext = $storageAccount.Context
          $container = Get-AzStorageContainer -Name $containerName -Context $storageContext
          $blob = Get-AzStorageBlob -Container $containerName -Context $storageContext -Blob $blobName -ErrorAction SilentlyContinue
          if ($blob) {
            $blobContent = $blob.ICloudBlob.DownloadText()
            $blobContent += "$buildId,$timestamp,$buildNumber`n"
            $blob.ICloudBlob.UploadText($blobContent)
          }
          else {
            $blobContent = "$buildId,$timestamp,$buildNumber`n"
            Set-AzStorageBlobContent -Container $containerName -Context $storageContext -Blob $blobName -Text $blobContent
          }

    - task: PublishBuildArtifacts@1
      displayName: 'Publish Artifacts'
      inputs:
        pathtoPublish: '$(Build.ArtifactStagingDirectory)'
        artifactName: '${{ parameters.artifactName }}'
        publishLocation: 'Container'