variables:
  backendResourceGroupName: 'rg-tf-backend'
  backendStorageAccountName: 'stacctfrajanaka77'
  backendContainerName: 'terraform'
  moduleName: "vnetdemo"
  artifactName: "Demo"
  environment: "prod"
  poolName: 'IACS Pool'