variables:
  backendResourceGroupName: 'rg-tf-backend'
  backendStorageAccountName: 'stacctfrajanaka77'
  backendContainerName: 'terraform'
  backendRemoteContainerName: 'remotestate'
  moduleName: "vnetdemo"
  artifactName: "Demo"
  environment: "prod"
  poolName: 'IACS Pool'
  buildType: 'current'
  buildVersion: 'latest'
  buildId: ''